// Generated by CoffeeScript 1.9.2
(function() {
  var pongular;

  pongular = require('pongular').pongular;

  pongular.module('pong-base').service('Firebase', function() {
    return require('firebase');
  }).service('$q', function() {
    return require('q');
  }).service('$watch', function() {
    return function(model) {
      var i, indexer, len, ref, results;
      ref = model.indexers;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        indexer = ref[i];
        indexer.start();
        results.push(console.log('started index watcher for', indexer.model.name(), indexer.field));
      }
      return results;
    };
  });

}).call(this);
