// Generated by CoffeeScript 1.9.2
(function() {
  var di;

  di = (typeof window !== 'undefined') && window.angular || require('pongular').pongular;

  di.module('pong-base').value('PBShared', function() {
    return 'Something both sides share';
  });

}).call(this);
